# -*- coding: utf-8 -*-
"""Project3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ew-5mQ0za-USynXJd2409g-49vk9Hcv4
"""

#!/usr/bin/python

#import libraries
import Adafruit_BBIO.GPIO as GPIO
import time

#create variables for pin A,B..F,G
A = "P8_7"
B = "P8_8"
C = "P8_10"
D = "P8_12"
E = "P8_14"
F = "P8_16"
G = "P8_18"

#initialize the pin as an OUTPUT
GPIO.setup(A, GPIO.OUT)
GPIO.setup(B, GPIO.OUT)
GPIO.setup(C, GPIO.OUT)
GPIO.setup(D, GPIO.OUT)
GPIO.setup(E, GPIO.OUT)
GPIO.setup(F, GPIO.OUT)
GPIO.setup(G, GPIO.OUT)

#loop forever
while True:
    printZero()
    time.sleep(1) #stay idle for 1 second
    printOne()
    time.sleep(1) #stay idle for 1 second
    printTwo()
    time.sleep(1) #stay idle for 1 second
    printThree()
    time.sleep(1) #stay idle for 1 second
    printFour()
    time.sleep(1) #stay idle for 1 second
    printFive()
    time.sleep(1) #stay idle for 1 second
    printSix()
    time.sleep(1) #stay idle for 1 second
    printSeven()
    time.sleep(1) #stay idle for 1 second
    printEight()
    time.sleep(1) #stay idle for 1 second
    printNine()
    time.sleep(1) #stay idle for 1 second


def printZero():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.HIGH) 
  GPIO.output(F, GPIO.HIGH) 
  GPIO.output(G, GPIO.LOW) 

def printOne():
  GPIO.output(A, GPIO.LOW)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.LOW) 
  GPIO.output(E, GPIO.LOW) 
  GPIO.output(F, GPIO.LOW)
  GPIO.output(G, GPIO.LOW)

def printTwo():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.LOW) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.HIGH) 
  GPIO.output(F, GPIO.LOW) 
  GPIO.output(G, GPIO.HIGH)  

def printThree():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.LOW) 
  GPIO.output(F, GPIO.LOW) 
  GPIO.output(G, GPIO.HIGH)  

def printFour():
  GPIO.output(A, GPIO.LOW)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.LOW) 
  GPIO.output(E, GPIO.LOW) 
  GPIO.output(F, GPIO.HIGH) 
  GPIO.output(G, GPIO.HIGH)  

def printFive():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.LOW) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.LOW) 
  GPIO.output(F, GPIO.HIGH) 
  GPIO.output(G, GPIO.HIGH)  

def printSix():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.LOW) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.HIGH) 
  GPIO.output(F, GPIO.HIGH) 
  GPIO.output(G, GPIO.HIGH)  

def printSeven():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.LOW) 
  GPIO.output(E, GPIO.LOW) 
  GPIO.output(F, GPIO.LOW) 
  GPIO.output(G, GPIO.LOW)  

def printEight():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.HIGH) 
  GPIO.output(F, GPIO.HIGH) 
  GPIO.output(G, GPIO.HIGH)  

def printNine():
  GPIO.output(A, GPIO.HIGH)
  GPIO.output(B, GPIO.HIGH) 
  GPIO.output(C, GPIO.HIGH) 
  GPIO.output(D, GPIO.HIGH) 
  GPIO.output(E, GPIO.LOW) 
  GPIO.output(F, GPIO.HIGH) 
  GPIO.output(G, GPIO.HIGH)